source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef'
gem 'chefspec'
gem 'cookstyle'
gem 'fauxhai'
gem 'foodcritic'
gem 'github_changelog_generator'
gem 'inspec'
gem 'kitchen-digitalocean'
gem 'kitchen-dokken'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'rainbow'
gem 'rake'
gem 'rubocop'
gem 'stove'
